-- MySQL Script generated by MySQL Workbench
-- 02/20/18 07:16:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sakila` ;
USE `sakila` ;

-- -----------------------------------------------------
-- Table `sakila`.`t004archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t004archivo` (
  `cod_archivo` INT NOT NULL,
  `cod_tip_archivo` VARCHAR(50) NULL,
  `des_nom_archivo` VARCHAR(100) NULL,
  `dat_archivo` BLOB NULL,
  `cod_estado` CHAR(1) NULL COMMENT 'O: optimizado\nN: normal',
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_archivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t009usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t009usuario` (
  `cod_usuario` INT NOT NULL,
  `des_correo` VARCHAR(50) NULL,
  `num_telef` VARCHAR(15) NULL,
  `num_token` INT NULL,
  `fec_gen_token` DATETIME NULL,
  `des_pass` CHAR(200) NULL,
  `cod_estado` CHAR(1) NULL COMMENT 'T: temporal\nA: activo',
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t005mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t005mensaje` (
  `cod_mensaje` INT NOT NULL,
  `cod_usu_emisor` INT NULL,
  `cod_usu_recep` INT NULL,
  `fec_envio` DATETIME NULL COMMENT 'Considerar para ordenamiento en el chat',
  `fec_recep` DATETIME NULL,
  `fec_lectura` DATETIME NULL,
  `des_mensaje` VARCHAR(200) NULL,
  `cod_archivo` INT NULL,
  `cod_arc_optimo` INT NULL,
  `cod_estado` CHAR(1) NULL COMMENT 'E :envio\nR: recepción\nL: lectura',
  `ind_visu_emisor` TINYINT(1) NULL,
  `ind_visu_recep` TINYINT(1) NULL,
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_mensaje`),
  INDEX `fk_t004_idx` (`cod_archivo` ASC),
  INDEX `fk_t004_1_idx` (`cod_arc_optimo` ASC),
  INDEX `fk_t009_0_idx` (`cod_usu_emisor` ASC),
  INDEX `fk_t009_1_idx` (`cod_usu_recep` ASC),
  CONSTRAINT `fk_t004_0`
    FOREIGN KEY (`cod_archivo`)
    REFERENCES `sakila`.`t004archivo` (`cod_archivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t004_1`
    FOREIGN KEY (`cod_arc_optimo`)
    REFERENCES `sakila`.`t004archivo` (`cod_archivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t009_0`
    FOREIGN KEY (`cod_usu_emisor`)
    REFERENCES `sakila`.`t009usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t009_1`
    FOREIGN KEY (`cod_usu_recep`)
    REFERENCES `sakila`.`t009usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t012maestro_param`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t012maestro_param` (
  `cod_maestro` INT NOT NULL,
  `des_maestro` VARCHAR(50) NULL,
  `des_abrev` VARCHAR(10) NULL,
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_maestro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t010parametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t010parametro` (
  `cod_param` INT NOT NULL,
  `cod_maestro` INT NULL COMMENT 'tipos de documento\n',
  `des_param` VARCHAR(50) NULL,
  `des_abrev` VARCHAR(10) NULL,
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_param`),
  INDEX `fk_t012_idx` (`cod_maestro` ASC),
  CONSTRAINT `fk_t012`
    FOREIGN KEY (`cod_maestro`)
    REFERENCES `sakila`.`t012maestro_param` (`cod_maestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t014plantilla_email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t014plantilla_email` (
  `cod_plantilla` INT NOT NULL,
  `des_asunto` VARCHAR(50) NULL,
  `des_cuerpo` VARCHAR(200) NULL,
  `cod_estado` INT NULL,
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_plantilla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t015notif_email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t015notif_email` (
  `cod_noti_email` INT NOT NULL,
  `cod_plantilla` INT NULL,
  `des_data` VARCHAR(200) NULL,
  `fec_envio` DATETIME NULL,
  `cod_usu_dest` INT NULL,
  `cod_estado` CHAR(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_noti_email`),
  INDEX `fk_t014_idx` (`cod_plantilla` ASC),
  CONSTRAINT `fk_t014`
    FOREIGN KEY (`cod_plantilla`)
    REFERENCES `sakila`.`t014plantilla_email` (`cod_plantilla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t006notif_mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t006notif_mensaje` (
  `cod_notimensaje` INT NOT NULL,
  `cod_mensaje` INT NULL,
  `cod_noti_email` INT NULL,
  `ind_atendido` TINYINT(1) NULL,
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_notimensaje`),
  INDEX `fk_t000mensaje_idx` (`cod_mensaje` ASC),
  INDEX `fk_t015_idx` (`cod_noti_email` ASC),
  CONSTRAINT `fk_t005`
    FOREIGN KEY (`cod_mensaje`)
    REFERENCES `sakila`.`t005mensaje` (`cod_mensaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t015`
    FOREIGN KEY (`cod_noti_email`)
    REFERENCES `sakila`.`t015notif_email` (`cod_noti_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t011ubigeo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t011ubigeo` (
  `cod_ubigeo` INT NOT NULL,
  `des_nombre` VARCHAR(45) NULL,
  `cod_ubi_padre` INT NULL,
  `num_nivel` INT(1) NULL,
  `cod_estado` CHAR(1) NULL,
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_ubigeo`),
  INDEX `fk_t011_idx` (`cod_ubi_padre` ASC),
  CONSTRAINT `fk_t011`
    FOREIGN KEY (`cod_ubi_padre`)
    REFERENCES `sakila`.`t011ubigeo` (`cod_ubigeo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t001persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t001persona` (
  `cod_persona` INT NOT NULL,
  `cod_usuario` INT NULL,
  `cod_tip_doc` INT NULL,
  `num_doc` VARCHAR(15) NULL,
  `des_apellidos` VARCHAR(50) NULL,
  `des_nombres` VARCHAR(50) NULL,
  `cod_sexo` INT NULL,
  `des_correo` VARCHAR(50) NULL,
  `num_telef` VARCHAR(15) NULL,
  `cod_dir_ubigeo` INT NULL COMMENT 'Código del último nivel',
  `des_direccion` VARCHAR(70) NULL,
  `num_lat_dir` DECIMAL(20,5) NULL,
  `num_lon_dir` DECIMAL(20,5) NULL,
  `ind_activ_posi` TINYINT(1) NULL,
  `fec_nacim` DATETIME NULL,
  `ind_cliente` TINYINT(1) NULL,
  `ind_espec` TINYINT(1) NULL,
  `ind_dispon` TINYINT(1) NULL,
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_persona`),
  INDEX `fk_t009_idx` (`cod_usuario` ASC),
  INDEX `fk_t011_idx` (`cod_dir_ubigeo` ASC),
  CONSTRAINT `fk_t009`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `sakila`.`t009usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t011`
    FOREIGN KEY (`cod_dir_ubigeo`)
    REFERENCES `sakila`.`t011ubigeo` (`cod_ubigeo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t003especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t003especialidad` (
  `cod_espec` INT NOT NULL,
  `des_nom_espec` VARCHAR(50) NULL,
  `des_espec` VARCHAR(200) NULL,
  `ind_activo` TINYINT(1) NULL,
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_espec`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t002experto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t002experto` (
  `cod_experto` INT NOT NULL,
  `cod_persona` INT NULL,
  `cod_espec` INT NULL,
  `des_resumen` VARCHAR(50) NULL,
  `des_detalle` VARCHAR(250) NULL,
  `ind_dispon` TINYINT(1) NULL,
  `ind_activo` TINYINT(1) NULL,
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_experto`),
  INDEX `fk_t003_idx` (`cod_espec` ASC),
  INDEX `fk_t001_idx` (`cod_persona` ASC),
  CONSTRAINT `fk_t001`
    FOREIGN KEY (`cod_persona`)
    REFERENCES `sakila`.`t001persona` (`cod_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t003`
    FOREIGN KEY (`cod_espec`)
    REFERENCES `sakila`.`t003especialidad` (`cod_espec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t007archivo_expert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t007archivo_expert` (
  `cod_arch_expert` INT NOT NULL,
  `cod_experto` INT NULL,
  `cod_archivo` INT NULL,
  `ind_activo` TINYINT(1) NULL,
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_arch_expert`),
  INDEX `fk_t002_idx` (`cod_experto` ASC),
  INDEX `fk_t004_idx` (`cod_archivo` ASC),
  CONSTRAINT `fk_t002`
    FOREIGN KEY (`cod_experto`)
    REFERENCES `sakila`.`t002experto` (`cod_experto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t004`
    FOREIGN KEY (`cod_archivo`)
    REFERENCES `sakila`.`t004archivo` (`cod_archivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t008comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t008comentario` (
  `cod_coment` INT NOT NULL,
  `cod_experto` INT NULL,
  `des_coment` VARCHAR(200) NULL,
  `num_calif` INT(1) NULL,
  `ind_activo` TINYINT(1) NULL,
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_coment`),
  INDEX `fk_t002_idx` (`cod_experto` ASC),
  CONSTRAINT `fk_t002`
    FOREIGN KEY (`cod_experto`)
    REFERENCES `sakila`.`t002experto` (`cod_experto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t013diccionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t013diccionario` (
  `cod_palabra` INT NOT NULL,
  `des_palabra` VARCHAR(30) NULL,
  `cod_tipo` INT NULL COMMENT 'N: no permitida',
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_palabra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t018sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t018sesion` (
  `cod_sesion` INT NOT NULL,
  `cod_usuario` INT NULL,
  `cod_tip_disp` INT NULL,
  `fec_ini_ses` DATETIME NULL,
  `num_lati` DECIMAL(20,5) NULL,
  `num_long` DECIMAL(20,5) NULL,
  `num_ip` VARCHAR(20) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_sesion`),
  INDEX `fk_t009_idx` (`cod_usuario` ASC),
  CONSTRAINT `fk_t009`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `sakila`.`t009usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t016servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t016servicio` (
  `cod_servicio` INT NOT NULL,
  `fec_ini_serv` DATETIME NULL,
  `fec_fin_serv` DATETIME NULL,
  `cod_estado` INT NULL,
  `cod_experto` INT NULL,
  `cod_usu_clien` INT NULL,
  `num_calif_clien` INT(1) NULL,
  `des_coment` VARCHAR(200) NULL,
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_servicio`),
  INDEX `fk_t002_idx` (`cod_experto` ASC),
  INDEX `fk_t009_idx` (`cod_usu_clien` ASC),
  CONSTRAINT `fk_t002`
    FOREIGN KEY (`cod_experto`)
    REFERENCES `sakila`.`t002experto` (`cod_experto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t009`
    FOREIGN KEY (`cod_usu_clien`)
    REFERENCES `sakila`.`t009usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`t017archivo_serv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`t017archivo_serv` (
  `cod_arch_serv` INT NOT NULL,
  `cod_servicio` INT NULL,
  `cod_archivo` INT NULL,
  `ind_elim` TINYINT(1) NULL,
  `fec_crea` DATETIME NULL,
  `cod_usucrea` VARCHAR(15) NULL,
  `fec_mod` DATETIME NULL,
  `cod_usumod` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_arch_serv`),
  INDEX `fk_t004_idx` (`cod_archivo` ASC),
  INDEX `fk_t016_idx` (`cod_servicio` ASC),
  CONSTRAINT `fk_t016`
    FOREIGN KEY (`cod_servicio`)
    REFERENCES `sakila`.`t016servicio` (`cod_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t004`
    FOREIGN KEY (`cod_archivo`)
    REFERENCES `sakila`.`t004archivo` (`cod_archivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
